# SPDX-FileCopyrightText: 2024 Baptiste Legouix
# SPDX-License-Identifier: GPL-3.0-or-later

name: test
on:
  push: { branches: [ main ] }
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref == github.ref_protected && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  id_repo:
    runs-on: ubuntu-latest
    outputs: { in_base_repo: '${{ steps.identify_repo.outputs.in_base_repo }}' }
    steps:
    - name: Identify repository
      id: identify_repo
      run: |
        echo "in_base_repo=${{ (github.event_name == 'push' && github.repository == 'blegouix/similie') || github.event.pull_request.head.repo.full_name == 'blegouix/similie' }}" >> "$GITHUB_OUTPUT"

  docker-build:
    needs: id_repo
    runs-on: ubuntu-latest
    steps:
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@v1.3.1
      with: { tool-cache: true, large-packages: false }
    - name: Checkout built branch
      uses: actions/checkout@v4
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build
      run: |
        DOCKER_BUILDKIT=1 docker build \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from ghcr.io/blegouix/similie/doxygen \
          -t ghcr.io/blegouix/similie/doxygen \
          -t ghcr.io/blegouix/similie/doxygen:${GITHUB_SHA:0:7} \
          docker/doxygen
    - name: Publish image for current SHA
      if: needs.id_repo.outputs.in_base_repo == 'true'
      run: |
        docker push ghcr.io/blegouix/similie/doxygen:${GITHUB_SHA:0:7}
    - name: Publish latest (default) image
      if: github.event_name == 'push' && github.ref_name == 'main' && needs.id_repo.outputs.in_base_repo == 'true'
      run: |
        docker push ghcr.io/blegouix/similie/doxygen
    - name: Create image tarball
      if: needs.id_repo.outputs.in_base_repo == 'false'
      run: |
        docker save ghcr.io/blegouix/similie/doxygen:${GITHUB_SHA:0:7} > doxygen.tar
    - name: Generate docker artifact from image
      if: needs.id_repo.outputs.in_base_repo == 'false'
      uses: actions/upload-artifact@v4
      with:
        name: doxygen-artifact
        path: doxygen.tar
        retention-days: 1

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.18
      with:
        source: 'examples/ src/ tests/'
        exclude: ''
        extensions: 'hpp,cpp'
        clangFormatVersion: 18
    - name: Prefer 'if defined' over 'ifdef'
      run: if grep -R "ifdef" benchmarks/ examples/ include/ddc/ install_test/ tests/; then exit 1; fi
    - name: Find modifications of Kokkos reserved macros
      run: if grep -RE "(define|undef) KOKKOS_" benchmarks/ examples/ include/ddc/ install_test/ tests/; then exit 1; fi
    - name: Find trailing whitespaces
      run: find . -not -path './vendor/*' -type f \( -name '*.[c|h]pp' -o -name 'CMakeLists.txt' -o -name '*.cmake' -o -name '*.md' -o -name '*.py' \) -exec ./vendor/ddc/bin/trailing_spaces --Werror '{}' '+'
    - name: REUSE Compliance Check
      if: always()
      uses: fsfe/reuse-action@v4
