# SPDX-FileCopyrightText: 2024 Baptiste Legouix
# SPDX-License-Identifier: GPL-3.0-or-later

name: test
on:
  push: { branches: [ main ] }
  pull_request:
concurrency:
  group: ${{ github.workflow }}-${{ github.ref == github.ref_protected && github.run_id || github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: DoozyX/clang-format-lint-action@v0.18
      with:
        source: 'examples/ src/ tests/'
        exclude: ''
        extensions: 'hpp,cpp'
        clangFormatVersion: 18
    - name: Prefer 'if defined' over 'ifdef'
      run: if grep -R "ifdef" examples/ src/ tests/; then exit 1; fi
    - name: Find modifications of Kokkos reserved macros
      run: if grep -RE "(define|undef) KOKKOS_" examples/ src/ tests/; then exit 1; fi
    - name: REUSE Compliance Check
      if: always()
      uses: fsfe/reuse-action@v4
